apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-buildtime
  name: echo-buildtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-buildtime
  template:
    metadata:
      labels:
        app: echo-buildtime
    spec:
      containers:
      - image: 192.168.1.10:8443/echo-buildtime
        name: echo-buildtime
        resources:
          limits:
            memory: 250Mi
